project:
  type: website
  output-dir: docs

website:
  title: "Michael Scherzer"
  
  
  page-footer:
    left: "A work by Michael Scherzer"
    right:
      - icon: github
        href: https://github.com
      - icon: twitter
        href: https://twitter.com
      - icon: envelope
        href: mailto:michael.scherzer@hci.utah.edu
  
  
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        file: protect/index.html
      - text: "publications"
        file: about.qmd
      - text: "test"
        file: about.qmd
      - sidebar:cv
        

  sidebar:
  
      - id: cv
        title: "CV/Resume"
        
        style: "docked"
        background: light 
        collapse-level: 2
        contents:
        - text: "CV"
          href: pdf/Curriculum_Vitae.pdf
        - text: "Resume"
          href: pdf/Curriculum_Vitae.pdf
       


format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

